# Generated by Django 3.0.5 on 2021-12-23 09:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Folder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Titre')),
                ('ranking', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('organisateur', models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, related_name='folders', to='account.Organisateur')),
            ],
        ),
        migrations.CreateModel(
            name='Sequence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10)),
                ('title', models.CharField(blank=True, default='Ma nouvelle séquence', max_length=255, null=True, verbose_name='Titre')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Date de création')),
                ('ranking', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('temporisation', models.BooleanField(default=0, verbose_name='mode continu ?')),
                ('authentification', models.BooleanField(default=0, verbose_name='Authentification ?')),
                ('pseudonyme', models.BooleanField(default=0, verbose_name='Pseudonyme ?')),
                ('competition', models.BooleanField(default=0, verbose_name='Compétition ?')),
                ('terminal', models.BooleanField(default=0, verbose_name='Afficage des diapositives sur le terminal des participants ?')),
                ('displayresult', models.BooleanField(default=0, verbose_name='Résultats visibles par defaut ?')),
                ('folder', models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, related_name='sequences', to='sequence.Folder')),
                ('organisateur', models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, related_name='sequences', to='account.Organisateur')),
            ],
        ),
        migrations.CreateModel(
            name='Ranking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appid', models.CharField(blank=True, editable=False, max_length=255, null=True)),
                ('position', models.PositiveIntegerField(blank=True, default=0, editable=False, null=True)),
                ('sequence', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='rankings', to='sequence.Sequence')),
            ],
        ),
    ]
