# Generated by Django 3.0.5 on 2021-12-22 17:52

import account.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Folder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Titre')),
                ('ranking', models.PositiveIntegerField(blank=True, default=0, editable=False, null=True)),
                ('teacher', models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, related_name='folders', to='account.Teacher')),
            ],
        ),
        migrations.CreateModel(
            name='Sequence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, default=account.models.generate_code, max_length=100, unique=True, verbose_name='Code')),
                ('icon', models.CharField(blank=True, editable=False, max_length=255, null=True)),
                ('title', models.CharField(blank=True, default='Mon nouvel évènement', max_length=255, null=True, verbose_name='Titre')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Date de création')),
                ('ranking', models.PositiveIntegerField(blank=True, default=0, editable=False, null=True)),
                ('folder', models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, related_name='events', to='sequence.Folder')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
