# Generated by Django 3.0.5 on 2021-12-23 07:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sequence', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ranking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appid', models.CharField(blank=True, editable=False, max_length=255, null=True)),
                ('position', models.PositiveIntegerField(blank=True, default=0, editable=False, null=True)),
                ('sequence', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='rankings', to='sequence.Sequence')),
            ],
        ),
    ]
