# Generated by Django 3.0.5 on 2021-12-23 09:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sequence', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sequence',
            name='folder',
            field=models.ForeignKey(blank=True, default='', null=None, on_delete=django.db.models.deletion.CASCADE, related_name='sequences', to='sequence.Folder'),
        ),
    ]
