# Generated by Django 3.0.5 on 2022-01-03 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sequence', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='play',
            name='date_end',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='play',
            name='date_start',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
