# Generated by Django 3.0.5 on 2021-12-23 10:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sequence', '0002_auto_20211223_1058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sequence',
            name='folder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sequences', to='sequence.Folder'),
        ),
    ]
