# Generated by Django 3.0.5 on 2022-01-10 11:45

from django.db import migrations, models
import sequence.models


class Migration(migrations.Migration):

    dependencies = [
        ('sequence', '0002_auto_20220103_2326'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='legendimage',
            field=models.ImageField(blank=True, default='', null=True, upload_to=sequence.models.question_directory_path, verbose_name='Image à legender'),
        ),
    ]
