# Generated by Django 3.0.5 on 2021-12-23 10:04

import account.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sequence', '0003_auto_20211223_1101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sequence',
            name='code',
            field=models.CharField(blank=True, default=account.models.generate_code, max_length=100, unique=True, verbose_name='Code'),
        ),
    ]
