# Generated by Django 3.0.5 on 2021-12-24 12:59

import account.models
from django.db import migrations, models
import django.db.models.deletion
import sequence.models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
        ('sequence', '0004_auto_20211223_1104'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, default=account.models.generate_code, max_length=100, unique=True, verbose_name='Code')),
                ('title', models.CharField(blank=True, default='Ma nouvelle séquence', max_length=255, null=True, verbose_name='Titre')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Date de création')),
                ('imagefile', models.ImageField(blank=True, default='', null=True, upload_to=sequence.models.question_directory_path, verbose_name='Image')),
                ('score', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('atype', models.PositiveIntegerField(default=0)),
                ('is_share', models.BooleanField(default=0, verbose_name='Mutualisé ?')),
                ('timer', models.BooleanField(default=0, verbose_name='Compte à rebours ?')),
                ('is_publish', models.BooleanField(default=0, verbose_name='Publié ?')),
                ('start_publish', models.DateTimeField(blank=True, null=True, verbose_name='A partir de')),
                ('stop_publish', models.DateTimeField(blank=True, null=True, verbose_name='Date de verrouillage')),
                ('liker', models.BooleanField(default=0, verbose_name='Like')),
                ('multiple', models.BooleanField(default=0, verbose_name='Réponse multiple')),
                ('ranking', models.PositiveIntegerField(blank=True, default=0, editable=False, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Answerplayer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(blank=True, max_length=255, null=True, verbose_name='Réponse')),
                ('score', models.PositiveIntegerField(default=0, editable=False)),
                ('timer', models.CharField(editable=False, max_length=255)),
                ('is_correct', models.BooleanField(default=0, editable=False)),
                ('activity', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='answers_player', to='sequence.Activity')),
                ('participant', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='answers_player', to='account.Participant')),
            ],
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imageanswer', models.ImageField(blank=True, default='', null=True, upload_to=sequence.models.choice_directory_path, verbose_name='Image')),
                ('label', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Réponse')),
                ('is_correct', models.BooleanField(default=0, verbose_name='Réponse correcte ?')),
                ('associate', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Association')),
                ('imageassociate', models.ImageField(blank=True, default='', null=True, upload_to=sequence.models.choice_directory_path, verbose_name='Image')),
                ('textarea', models.TextField(blank=True, default='', null=True, verbose_name='Texte')),
                ('activity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='sequence.Activity')),
            ],
        ),
        migrations.AlterField(
            model_name='sequence',
            name='displayresult',
            field=models.BooleanField(default=0, verbose_name='Résultats visibles par défaut ?'),
        ),
        migrations.AlterField(
            model_name='sequence',
            name='terminal',
            field=models.BooleanField(default=0, verbose_name='Affichage des diapositives sur le terminal des participants ?'),
        ),
        migrations.DeleteModel(
            name='Ranking',
        ),
        migrations.AddField(
            model_name='activity',
            name='sequence',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='sequence.Sequence'),
        ),
    ]
