# Generated by Django 3.0.5 on 2021-12-25 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sequence', '0005_auto_20211224_1359'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='is_score',
            field=models.BooleanField(default=0, verbose_name='Score ?'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='score',
            field=models.PositiveIntegerField(blank=True, default=1000, null=True),
        ),
        migrations.AlterField(
            model_name='activity',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Ecrire la question que vous souhaitez poser à votre audience'),
        ),
    ]
