# Generated by Django 3.0.5 on 2021-12-25 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sequence', '0006_auto_20211225_0842'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='is_timer',
            field=models.BooleanField(default=0, verbose_name='Compte à rebours ?'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='timer',
            field=models.BooleanField(default=0, verbose_name='Temps'),
        ),
    ]
