# Generated by Django 3.0.5 on 2021-12-25 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sequence', '0007_auto_20211225_0845'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='is_shuffle',
            field=models.BooleanField(default=0, verbose_name='Shuffle ?'),
        ),
    ]
