# Generated by Django 3.0.5 on 2021-12-28 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
        ('sequence', '0008_activity_is_shuffle'),
    ]

    operations = [
        migrations.AddField(
            model_name='sequence',
            name='is_active',
            field=models.BooleanField(default=0, editable=False, verbose_name='En cours ?'),
        ),
        migrations.AddField(
            model_name='sequence',
            name='participants',
            field=models.ManyToManyField(blank=True, related_name='sequences', to='account.Participant'),
        ),
    ]
