# Generated by Django 3.0.5 on 2021-12-28 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
        ('sequence', '0010_auto_20211228_1303'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sequence',
            name='qrcode',
        ),
        migrations.AddField(
            model_name='sequence',
            name='participants',
            field=models.ManyToManyField(blank=True, related_name='sequences', to='account.Participant'),
        ),
    ]
