# Generated by Django 3.0.5 on 2021-12-29 12:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sequence', '0011_auto_20211228_1304'),
    ]

    operations = [
        migrations.AddField(
            model_name='answerplayer',
            name='choice',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='answers_player', to='sequence.Choice'),
        ),
    ]
