# Generated by Django 3.0.5 on 2022-01-03 11:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
        ('sequence', '0012_answerplayer_choice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answerplayer',
            name='timer',
        ),
        migrations.AddField(
            model_name='answerplayer',
            name='duration',
            field=models.CharField(default=0, editable=False, max_length=255, verbose_name='durée'),
        ),
        migrations.AlterField(
            model_name='answerplayer',
            name='activity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='answers_player', to='sequence.Activity'),
        ),
        migrations.AlterField(
            model_name='answerplayer',
            name='answer',
            field=models.CharField(blank=True, max_length=1024, null=True, verbose_name='Réponse'),
        ),
        migrations.AlterField(
            model_name='answerplayer',
            name='choice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='answers_player', to='sequence.Choice'),
        ),
        migrations.AlterField(
            model_name='answerplayer',
            name='participant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='answers_player', to='account.Participant'),
        ),
        migrations.AlterField(
            model_name='answerplayer',
            name='score',
            field=models.IntegerField(default=0, editable=False),
        ),
        migrations.CreateModel(
            name='Play',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('org_channel', models.CharField(help_text="channel de l'organisateur", max_length=60, null=True)),
                ('status', models.SmallIntegerField(default=0)),
                ('date_start', models.DateTimeField(blank=True)),
                ('date_end', models.DateTimeField(blank=True)),
                ('ranking', models.IntegerField(default=-1, help_text='la numero de la dernière activité terminée')),
                ('sequence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sequence.Sequence')),
            ],
        ),
        migrations.AddField(
            model_name='answerplayer',
            name='play',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='answers_player', to='sequence.Play'),
        ),
    ]
