# Generated by Django 3.0.5 on 2021-12-21 15:00

import account.models
from django.db import migrations, models
import django.db.models.deletion
import event.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(blank=True, default='', max_length=255, verbose_name='Réponse écrite')),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('vignette', models.ImageField(blank=True, default='', null=True, upload_to=event.models.question_directory_path, verbose_name="Vignette d'accueil")),
            ],
        ),
        migrations.CreateModel(
            name='Folder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Titre')),
                ('ranking', models.PositiveIntegerField(blank=True, default=0, editable=False, null=True)),
                ('teacher', models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, related_name='folders', to='account.Teacher')),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, default=account.models.generate_code, max_length=100, unique=True, verbose_name='Code')),
                ('icon', models.CharField(blank=True, editable=False, max_length=255, null=True)),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Titre')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Date de création')),
                ('ranking', models.PositiveIntegerField(blank=True, default=0, editable=False, null=True)),
                ('folder', models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, related_name='events', to='event.Folder')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imageanswer', models.ImageField(blank=True, default='', null=True, upload_to=event.models.choice_directory_path, verbose_name='Image')),
                ('answer', models.TextField(blank=True, default='', max_length=255, null=True, verbose_name='Réponse écrite')),
                ('is_correct', models.BooleanField(default=0, verbose_name='Réponse correcte ?')),
                ('question', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='event.Question')),
            ],
        ),
    ]
